title: "Zen | Blogspot Template Creator | Web Dev | Android Dev | 081545143654"

permalink: /:year/:month/:day/:title/

paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  
name: Zen
description: Developer
url: http://muhammadzaini.com

timezone: Asia/Makassar

komunitas:
  -
    gambar: /gambar/komunitas/blog.jpg
    link: https://chat.whatsapp.com/KBzZzO25l1mLoEatsjHWAw
    
menu:
  -
    nama: Portofolio
    link: http://muhammadzaini.com