permalink: /:title
skill:
- Vue
- Bootstrap
- PHP
- Javascript
- Jekyll
- MySQL
- YAML
- HTML
- CSS
- Fetch API
proyek_pribadi:
- link: https://mzaini30.js.org/catatan/#/
  gambar: https://i.ibb.co/XC42D5Z/Screenshot-2020-07-31-17-13-13-00.png
- link: https://mzaini30.js.org/efektif/#/
  gambar: https://i.ibb.co/L1yqK9Y/Screenshot-2020-07-31-17-23-47-63.png
- link: https://mzaini30.js.org/lapor-baca/#/
  gambar: https://i.ibb.co/pb9gFW8/Screenshot-2020-07-31-19-31-25-16.png
- link: https://mzaini30.js.org/kode/#/
  gambar: https://i.ibb.co/YjCNfx8/Screenshot-2020-07-31-19-34-20-05.png
- link: https://mzaini30.js.org/html-playground/
  gambar: https://i.ibb.co/1XqWm3H/Screenshot-2020-08-01-05-35-14-39.png
- link: https://murajaah.js.org/
  gambar: https://i.ibb.co/YDhjkvN/Screenshot-2020-08-01-05-42-46-21.png
- link: https://mzaini30.js.org/penata-letak/
  gambar: https://i.ibb.co/Dwq139J/Screenshot-2020-08-01-05-49-09-25.png
- link: https://mzaini30.js.org/mutabaah/
  gambar: https://i.ibb.co/1md2zvW/Screenshot-2020-08-01-05-51-03-40.png
- link: https://mzaini30.js.org/ide/
  gambar: https://i.ibb.co/cCGs0X5/Screenshot-2020-08-01-05-52-43-95.png
- link: https://mzaini30.js.org/covidgym/
  gambar: https://i.ibb.co/Qv0PWqG/Screenshot-2020-08-01-05-54-07-70.png
- link: https://mzaini30.js.org/covid19/
  gambar: https://i.ibb.co/HpDpWL3/Screenshot-2020-08-01-05-55-52-85.png
- link: https://kamus.rumahzen.my.id/
  gambar: https://i.ibb.co/XDDKfSP/Screenshot-2020-08-01-05-58-53-06.png
- link: https://mzaini30.js.org/color30/
  gambar: https://i.ibb.co/7JwjQDp/Screenshot-2020-08-01-06-00-51-59.png
proyek_komersial:
- link: http://panglimadelivery.com/
  gambar: https://i.ibb.co/KLcF8GZ/Screenshot-2020-08-01-20-04-38-56.png
pencapaian:
- https://mzaini30.nasihosting.com/efektif/badge.php/1
- https://github-contribution-stats.vercel.app/api/?username=mzaini30
- https://projecteuler.net/profile/mzaini30.png
- https://i.ibb.co/7Qx2PYn/j-Query-certificate.jpg
- https://i.ibb.co/g7yw5fn/HTML-certificate.jpg
- https://i.ibb.co/DQbyTtJ/SQL-certificate.jpg
- https://res.cloudinary.com/practicaldev/image/fetch/s--mvoi2vUk--/c_limit,f_auto,fl_progressive,q_80,w_180/https://dev-to-uploads.s3.amazonaws.com/uploads/badge/badge_image/2/1-year-badge.png
- https://res.cloudinary.com/practicaldev/image/fetch/s--ORkiIcqa--/c_limit,f_auto,fl_progressive,q_80,w_180/https://dev-to-uploads.s3.amazonaws.com/uploads/badge/badge_image/31/hacktoberfeststicker-01_copy.png
