# settingan dasar

url: http://muhammadzaini.com
lokasi: '/media/data/web/mzaini30.github.io (git)'
permalink: /:year/:month/:day/:title.html
title: Zen
description: Psikologi

# paginate

# paginate: 12

# pengumuman

# pengumuman:
#   isi: Tes
#   jenis: danger # info, success, warning, danger

# link

link:
  -
    judul: Project Euler
    link: https://projecteuler.net/profile/mzaini30.png
    icon: free-code-camp
  -
    judul: You Tube
    link: https://www.youtube.com/channel/UCvJYEicYS2Yvcr3hhsFU5-g
    icon: youtube-play
  -
    judul: Instagram
    link: https://www.instagram.com/mzaini30/
    icon: instagram
  -
    judul: Wattpad
    link: https://www.wattpad.com/user/mzaini30
    icon: pencil-square-o
  -
    judul: Medium
    link: https://medium.com/@mzaini30
    icon: medium
  -
    judul: Blog
    link: /blog.html
    icon: rss
  -
    judul: Facebook
    link: http://facebook.com/mzaini30
    icon: facebook-square
  -
    judul: 10 Fast Fingers
    link: https://10fastfingers.com/user/1452563/
    icon: keyboard-o
  -
    judul: Github
    link: http://github.com/mzaini30
    icon: github
  -
    judul: Play Store
    link: http://github.com/mzaini30
    icon: android
  -
    judul: Cloud
    link: http://gitlab.com/mzaini30/cloud
    icon: cloud
  -
    judul: Telegram
    link: http://t.me/mzaini30a
    icon: paper-plane
  -
    judul: Whatsapp
    link: https://api.whatsapp.com/send?phone=6281545143654
    icon: whatsapp
  -
    judul: Aplikasi Web
    link: https://github.com/mzaini30/web-apps
    icon: globe
  -
    judul: Email
    link: mailto:muhzaini30@gmail.com
    icon: envelope-o
  -
    judul: LINE
    link: http://line.me/ti/p/~mzaini30
    icon: heart-o

# iklan

harga_iklan: '1.003'
slot_iklan:
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'

# gambar default

gambar: https://img00.deviantart.net/e121/i/2017/198/c/2/fate_apocrypha_hd_wallpaper_by_tammypain-dbgp3hz.png

# stay connected

stay_connected:
  -
    judul: Aplikasi Web
    link: '#!'
  -
    judul: Github
    link: http://github.com/mzaini30
  -
    judul: Facebook
    link: http://facebook.com/mzaini30
  -
    judul: Telegram
    link: http://t.me/mzaini30a
  -
    judul: Whatsapp
    link: https://api.whatsapp.com/send?phone=6281545143654
  -
    judul: Play Store
    link: https://play.google.com/store/apps/dev?id=6751907367958089476
  -
    judul: 10 Fast Fingers
    link: https://10fastfingers.com/user/1452563/

# blogwalking

blogwalking:
  -
    judul: Ikatan Lembaga Mahasiswa Psikologi Indonesia
    link: http://ilmpi.org/
  -
    judul: Isy Karima
    link: https://www.youtube.com/channel/UCXX1KQrPS2tFsKkvPcHcTUw/videos
  -
    judul: Himpunan Psikologi Indonesia
    link: http://himpsi.or.id/
  -
    judul: American Psychological Association
    link: http://www.apa.org/
  -
    judul: Medium
    link: https://medium.com/
  -
    judul: Electronic Frontier Foundation
    link: https://www.eff.org/
  -
    judul: Free Code Camp
    link: https://medium.freecodecamp.org/
  -
    judul: Qonita
    link: http://qnitaaa.blogspot.co.id/
  -
    judul: Dewie Dean
    link: http://dewieajaa.blogspot.co.id/
  -
    judul: Heni Puspita
    link: http://www.henipuspita.net/
  -
    judul: Nova Nodiwa
    link: https://www.nodiwa.com/
  -
    judul: Rian Yulianto W
    link: https://medium.com/@kucingmeongs
  -
    judul: Rani Psikologi
    link: https://www.wattpad.com/user/hasannahrani
  -
    judul: Dewi Sampurna Wati
    link: https://www.wattpad.com/user/dewisampurnaw
  -
    judul: Japanese Station
    link: https://japanesestation.com/
  -
    judul: My Satnite
    link: https://www.mysatnite.com/
  -
    judul: Syufia
    link: http://syufiayaumma.blogspot.co.id/
  -
    judul: Kompi Teknologi Indonesia
    link: http://www.kompitech.me/
  -
    judul: Codepolitan
    link: https://www.codepolitan.com/articles
  -
    judul: Petani Kode
    link: https://www.petanikode.com/

# penghargaan

penghargaan:
  -
    tahun: 2018 
    judul: "Kecepatan Mengetik: 85 Kata per Menit"
    link: https://10fastfingers.com/user/1452563/
    tingkat: Internasional
  -
    tahun: 2018 
    judul: Mahasiswa Berprestasi
    link: https://s25.postimg.org/shsyq8a6n/Scan352.jpg
    tingkat: Prodi
  -
    tahun: 2017 
    judul: 'Peserta: Sosialisasi 4 Pilar MPR RI'
    link: https://s25.postimg.org/5gcdkhi8v/Scan351.jpg
    tingkat: Nasional
  -
    tahun: 2017 
    judul: 'Panitia: Rakoornas ILMPI'
    link: https://s25.postimg.org/8afixx4zj/Scan355.jpg
    tingkat: Nasional
  -
    tahun: 2016 
    judul: 'Peserta: Workshop Grafologi'
    link: https://s25.postimg.org/k1z9eqwf3/gambar_0002.jpg
    tingkat: Prodi
  -
    tahun: 2014 
    judul: 'Finalis: Web Desain'
    link: https://s25.postimg.org/oal5eau9r/Desain_web.jpg
    tingkat: Nasional
  -
    tahun: 2014 
    judul: 'Desain Terkreatif dan Inovatif: Web Desain'
    link: https://s25.postimg.org/clzzszban/gambar_0004.jpg
    tingkat: Nasional
  -
    tahun: 2013 
    judul: 'Juara 2: Lomba Blog'
    link: https://s25.postimg.org/nyclarrpb/gambar_0006.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2012 
    judul: 'Peserta: Lomba Kimia'
    link: https://s25.postimg.org/hww2b24tb/Kimia.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2012 
    judul: 'Juara 2: Pidato Bahasa Indonesia'
    link: https://s25.postimg.org/qf5ifeyhb/Pidato_bahasa_indonesia_2.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 2: Lomba Karya Tulis Ilmiah'
    link: https://s25.postimg.org/3qz5iic8f/gambar_0009.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 2: Karya Tulis'
    link: https://s25.postimg.org/5v0ogx3an/Karya_tulis.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 1: Cerdas Cermat'
    link: https://s25.postimg.org/h7d9yntz3/Cerdas_cermat.jpg
    tingkat: Mahad
  -
    tahun: 2011 
    judul: 'Peserta: Pidato Bahasa Indonesia'
    link: https://s25.postimg.org/4fz3s6mrz/Pidato_bahasa_indonesia.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2010 
    judul: 'Juara Harapan 1: Asah Terampil Matematika'
    link: https://s25.postimg.org/jcgh2fllr/gambar_0001.jpg
    tingkat: Provinsi
  -
    tahun: 2010 
    judul: 'Juara 1: Lomba Blog'
    link: https://s25.postimg.org/tzaa7v96n/gambar_0005.jpg
    tingkat: Sekolah
  -
    tahun: 2009 
    judul: 'Peserta: Olimpiade Matematika'
    link: https://s25.postimg.org/doa6bkrjz/gambar_0011.jpg
    tingkat: Nasional
  -
    tahun: 2009 
    judul: 'Peserta: Asah Terampil Matematika'
    link: https://s25.postimg.org/rupx6qa3z/gambar_0003.jpg
    tingkat: Provinsi
  -
    tahun: 2008 
    judul: 'Juara 2: Lomba Pidato Bahasa Inggris'
    link: https://s25.postimg.org/9f5g9c3pb/gambar_0010.jpg
    tingkat: Kota
  -
    tahun: 2006 
    judul: 'Juara 1: Lomba Kaligrafi'
    link: https://s25.postimg.org/fsujcn61b/gambar_0008.jpg
    tingkat: Kota
  -
    tahun: 2004 
    judul: 'Juara 2: Lomba Hapalan Juz Amma'
    link: https://s25.postimg.org/5vjijk3kf/gambar_0007.jpg
    tingkat: Kota

# aplikasi web

aplikasi_web:
  -
    link: /font
    judul: Font
  -
    link: /jumlah-satuan
    judul: Jumlah Satuan
  -
    link: /kaligrafi
    judul: Kaligrafi
  -
    link: /kontest
    judul: Kontest
  -
    link: /kontur
    judul: Kontur
  -
    link: /color30
    judul: Materialize Color
  -
    link: http://psikoweb.epizy.com/login/index.php
    judul: Psikoweb
  -
    link: /tambah-hari
    judul: Tambah Hari
  -
    link: /wa
    judul: Whatsapp Link Generator
